// One-off remediation script: restores the per-page color schemes (and, for
// auto-converted pages, the shared legacy-content styling + functional image
// maps) that were lost during this project's modernization work.
//
// Two paths, depending on whether a page's live content was produced by the
// automated modernize.js pass or hand-rebuilt this session:
//
// - Auto-converted pages (everything except Twin Peaks / Woody Allen): the
//   live file is fully regenerated by re-running the (now-fixed) transform()
//   from modernize.js against the page's true original (recovered from git
//   history at commit 9a172bce, before any modernization happened).
// - Hand-rebuilt pages (Twin Peaks, Woody Allen): body content is already
//   correct and verified -- only a light patch is applied (legacy-content
//   class + color style + link <style> block), never re-running transform(),
//   so the hand-crafted structure is untouched.
//
// Usage: node restore-colors.js [--apply]
//   Without --apply: dry run, reports counts + writes restore-colors-log.json.
//   With --apply: writes the changes.

const fs = require('fs');
const path = require('path');
const { execSync } = require('child_process');
const cheerio = require('cheerio');
const { transform, wrapDocument } = require('./modernize.js');

const ORIGIN_COMMIT = '9a172bce';
const HAND_REBUILT_RE = /^content\/(_Twin_Peaks|_Woody_Allen)\//;
const PRESENTATIONAL_BODY_ATTRS = ['bgcolor', 'link', 'alink', 'vlink', 'text', 'background'];

function gitShow(relPath) {
  const out = execSync(`git show ${ORIGIN_COMMIT}:"${relPath}"`, { maxBuffer: 1024 * 1024 * 20 });
  return out.toString('utf8');
}

function captureColors(html) {
  const $ = cheerio.load(html, { decodeEntities: false });
  const colors = {};
  for (const attr of PRESENTATIONAL_BODY_ATTRS) {
    const v = $('body').attr(attr);
    if (v) colors[attr] = v;
  }
  return colors;
}

function patchColorsOnly(liveHtml, colors) {
  const $ = cheerio.load(liveHtml, { decodeEntities: false });
  $('body').addClass('legacy-content');

  const styleParts = [];
  if (colors.bgcolor) styleParts.push(`background-color: ${colors.bgcolor}`);
  if (colors.background) styleParts.push(`background-image: url('${colors.background}')`);
  if (colors.text) styleParts.push(`color: ${colors.text}`);
  if (styleParts.length) $('body').attr('style', styleParts.join('; '));

  const linkRules = [];
  if (colors.link) linkRules.push(`a { color: ${colors.link}; }`);
  if (colors.vlink) linkRules.push(`a:visited { color: ${colors.vlink}; }`);
  if (colors.alink) linkRules.push(`a:active { color: ${colors.alink}; }`);
  if (linkRules.length) $('head').append(`<style>\n${linkRules.join('\n')}\n</style>`);

  return $.html();
}

function main() {
  const apply = process.argv.includes('--apply');

  const modernList = execSync(`git ls-tree -r --name-only ${ORIGIN_COMMIT} -- content/`, { maxBuffer: 1024 * 1024 * 20 })
    .toString('utf8')
    .trim()
    .split('\n')
    .filter((f) => f.endsWith('.modern.html'));

  console.log(`Found ${modernList.length} pages converted at the start of this session.`);

  let regenerated = 0;
  let colorPatched = 0;
  let skippedNoColors = 0;
  let missingLive = [];
  let errors = [];
  const log = [];

  for (const modernPath of modernList) {
    const rawPath = modernPath.replace(/\.modern\.html$/, '.html');
    // Poirot's raw paths at the origin commit still have the old "_ Poirot_*"
    // (space) folder names; the live files were later renamed to "_Poirot_*".
    const livePath = rawPath.replace('_ Poirot_', '_Poirot_');

    if (!fs.existsSync(livePath)) {
      missingLive.push({ modernPath, livePath });
      continue;
    }

    let originalHtml;
    try {
      originalHtml = gitShow(rawPath);
    } catch (err) {
      errors.push({ rawPath, reason: `git show failed: ${err.message}` });
      continue;
    }

    const isHandRebuilt = HAND_REBUILT_RE.test(livePath);

    if (isHandRebuilt) {
      const colors = captureColors(originalHtml);
      if (Object.keys(colors).length === 0) {
        skippedNoColors++;
        continue;
      }
      const liveHtml = fs.readFileSync(livePath, 'utf8');
      const patched = patchColorsOnly(liveHtml, colors);
      if (apply) fs.writeFileSync(livePath, patched, 'utf8');
      colorPatched++;
      log.push({ livePath, action: 'color-patched', colors });
    } else {
      let result;
      try {
        result = transform(originalHtml);
      } catch (err) {
        errors.push({ livePath, reason: `transform error: ${err.message}` });
        continue;
      }
      const out = wrapDocument(result.title, result.bodyHtml, result.colors);
      if (apply) fs.writeFileSync(livePath, out, 'utf8');
      regenerated++;
      log.push({ livePath, action: 'regenerated', colors: result.colors });
    }
  }

  console.log(`${apply ? 'Regenerated' : 'Would regenerate'} (auto-converted): ${regenerated}`);
  console.log(`${apply ? 'Color-patched' : 'Would color-patch'} (hand-rebuilt): ${colorPatched}`);
  console.log(`Hand-rebuilt pages with no colors to restore (left untouched): ${skippedNoColors}`);
  console.log(`Missing live file (skipped): ${missingLive.length}`);
  console.log(`Errors: ${errors.length}`);
  if (missingLive.length) console.log(JSON.stringify(missingLive, null, 2));
  if (errors.length) console.log(JSON.stringify(errors, null, 2));

  fs.writeFileSync('restore-colors-log.json', JSON.stringify({ log, missingLive, errors }, null, 2));
}

main();
