// One-off remediation script: restores the per-page color schemes (and, for
// auto-converted pages, the shared legacy-content styling + functional image
// maps) that were lost during this project's modernization work.
//
// Two paths, depending on whether a page's live content was produced by the
// automated modernize.js pass or hand-rebuilt this session:
//
// - Auto-converted pages (everything except Twin Peaks / Woody Allen): the
//   live file is fully regenerated by re-running the (now-fixed) transform()
//   from modernize.js against the page's true original (recovered from git
//   history at commit 9a172bce, before any modernization happened).
// - Hand-rebuilt pages (Twin Peaks, Woody Allen): body content is already
//   correct and verified -- only a light patch is applied (legacy-content
//   class + color style + link <style> block), never re-running transform(),
//   so the hand-crafted structure is untouched.
//
// Usage: node restore-colors.js [--apply]
//   Without --apply: dry run, reports counts + writes restore-colors-log.json.
//   With --apply: writes the changes.

const fs = require('fs');
const path = require('path');
const { execSync } = require('child_process');
const cheerio = require('cheerio');
const { transform, wrapDocument, normalizeColor } = require('./modernize.js');

const ORIGIN_COMMIT = '9a172bce';
const HAND_REBUILT_RE = /^content\/(_Twin_Peaks|_Woody_Allen)\//;
const PRESENTATIONAL_BODY_ATTRS = ['bgcolor', 'link', 'alink', 'vlink', 'text', 'background'];
const PRESENTATIONAL_COLOR_ATTRS = new Set(['bgcolor', 'link', 'alink', 'vlink', 'text']);

function gitShow(relPath) {
  const out = execSync(`git show ${ORIGIN_COMMIT}:"${relPath}"`, { maxBuffer: 1024 * 1024 * 20 });
  return out.toString('utf8');
}

function captureColors(html) {
  const $ = cheerio.load(html, { decodeEntities: false });
  const colors = {};
  for (const attr of PRESENTATIONAL_BODY_ATTRS) {
    const v = $('body').attr(attr);
    if (v) colors[attr] = PRESENTATIONAL_COLOR_ATTRS.has(attr) ? normalizeColor(v) : v;
  }
  // Some pages never set a body-level `text` attribute at all -- instead
  // nearly every individual element carries its own explicit
  // <font color>. Without a body `text` color to capture, the hand-rebuilt
  // page ends up with a captured bgcolor but no matching text color,
  // falling back to content.css's default dark gray -- invisible against
  // a dark/black restored background. Infer a reasonable default from
  // whichever font color appears most often across the page.
  if (!colors.text) {
    const counts = new Map();
    $('font[color]').each((_, el) => {
      const c = normalizeColor($(el).attr('color'));
      counts.set(c, (counts.get(c) || 0) + 1);
    });
    let best = null;
    let bestCount = 0;
    for (const [c, count] of counts) {
      if (count > bestCount) {
        best = c;
        bestCount = count;
      }
    }
    if (best) colors.text = best;
  }
  return colors;
}

const HEADING_SELECTOR =
  'body.legacy-content h1, body.legacy-content h2, body.legacy-content h3, ' +
  'body.legacy-content h4, body.legacy-content h5, body.legacy-content h6';

// Returns null if the page has nothing left to do (body already has a
// bgcolor/background/text style, a link-color rule for each of
// link/vlink/alink it should have, AND the heading-color fix) -- keeps
// this script safe to re-run without piling up duplicate <style> blocks.
// Each piece is checked independently (not just "does body have a style
// attribute") so a follow-up run can add e.g. a text color a previous run
// never had available (colors.text used to only come from a body `text`
// attribute; it can now also be inferred from font-color usage -- see
// captureColors) without re-adding bgcolor/link rules a second time.
function patchColorsOnly(liveHtml, colors) {
  const $ = cheerio.load(liveHtml, { decodeEntities: false });
  const bodyStyle = $('body').attr('style') || '';
  const hasHeadingFix = $('head style').toArray().some((el) => $(el).html().includes('body.legacy-content h6'));
  const existingLinkRules = $('head style')
    .toArray()
    .map((el) => $(el).html())
    .join('\n');

  const missingBgColor = colors.bgcolor && !/background-color\s*:/.test(bodyStyle);
  const missingBackground = colors.background && !/background-image\s*:/.test(bodyStyle);
  const missingText = colors.text && !/(?<!background-)color\s*:/.test(bodyStyle);
  const missingLink = colors.link && !existingLinkRules.includes('body.legacy-content a {');
  const missingVlink = colors.vlink && !existingLinkRules.includes('body.legacy-content a:visited');
  const missingAlink = colors.alink && !existingLinkRules.includes('body.legacy-content a:active');

  if (!missingBgColor && !missingBackground && !missingText && !missingLink && !missingVlink && !missingAlink && hasHeadingFix) {
    return null;
  }

  $('body').addClass('legacy-content');
  if (missingBgColor || missingBackground || missingText) {
    const styleParts = bodyStyle ? [bodyStyle] : [];
    if (missingBgColor) styleParts.push(`background-color: ${colors.bgcolor}`);
    if (missingBackground) styleParts.push(`background-image: url('${colors.background}')`);
    if (missingText) styleParts.push(`color: ${colors.text}`);
    $('body').attr('style', styleParts.join('; '));
  }

  // content.css hardcodes a default link color via `body.legacy-content
  // a` -- a bare `a { color: ... }` override (lower specificity) always
  // loses to that regardless of cascade order, silently keeping the
  // generic blue link color instead of this page's own link/vlink/alink.
  // Match content.css's own selector so the override actually wins.
  const linkRules = [];
  if (missingLink) linkRules.push(`body.legacy-content a { color: ${colors.link}; }`);
  if (missingVlink) linkRules.push(`body.legacy-content a:visited { color: ${colors.vlink}; }`);
  if (missingAlink) linkRules.push(`body.legacy-content a:active { color: ${colors.alink}; }`);
  if (linkRules.length) $('head').append(`<style>\n${linkRules.join('\n')}\n</style>`);

  // content.css hardcodes headings to a dark color for its own light-theme
  // default -- on a page with a restored dark background, that renders
  // dark-on-dark and headings just disappear. Override with the same
  // selector content.css uses (same specificity, later in the cascade wins).
  if (!hasHeadingFix && colors.text) {
    $('head').append(`<style>\n${HEADING_SELECTOR} { color: ${colors.text}; }\n</style>`);
  }

  return $.html();
}

function main() {
  const apply = process.argv.includes('--apply');

  const modernList = execSync(`git ls-tree -r --name-only ${ORIGIN_COMMIT} -- content/`, { maxBuffer: 1024 * 1024 * 20 })
    .toString('utf8')
    .trim()
    .split('\n')
    .filter((f) => f.endsWith('.modern.html'));

  console.log(`Found ${modernList.length} pages converted at the start of this session.`);

  let regenerated = 0;
  let colorPatched = 0;
  let alreadyPatched = 0;
  let skippedNoColors = 0;
  let missingLive = [];
  let errors = [];
  const log = [];

  for (const modernPath of modernList) {
    const rawPath = modernPath.replace(/\.modern\.html$/, '.html');
    // Poirot's raw paths at the origin commit still have the old "_ Poirot_*"
    // (space) folder names; the live files were later renamed to "_Poirot_*".
    const livePath = rawPath.replace('_ Poirot_', '_Poirot_');

    if (!fs.existsSync(livePath)) {
      missingLive.push({ modernPath, livePath });
      continue;
    }

    let originalHtml;
    try {
      originalHtml = gitShow(rawPath);
    } catch (err) {
      errors.push({ rawPath, reason: `git show failed: ${err.message}` });
      continue;
    }
    // The git-history snapshot predates the Poirot folder rename (see the
    // "Remove accidental Chips upload; rename Poirot folders..." commit),
    // so every re-run of this script was silently reintroducing the old,
    // now-broken "_ Poirot_*" (space) paths into freshly regenerated pages.
    // Also fixes a genuine pre-existing typo in the original site itself
    // ("../ _Poirot_Episodes" with a stray space) while we're in here.
    originalHtml = originalHtml
      .replace(/_ Poirot_Casts/g, '_Poirot_Casts')
      .replace(/_ Poirot_Editions/g, '_Poirot_Editions')
      .replace(/_ Poirot_Locations/g, '_Poirot_Locations')
      .replace(/\/\s+_Poirot_Episodes/g, '/_Poirot_Episodes');

    const isHandRebuilt = HAND_REBUILT_RE.test(livePath);

    if (isHandRebuilt) {
      const colors = captureColors(originalHtml);
      if (Object.keys(colors).length === 0) {
        skippedNoColors++;
        continue;
      }
      const liveHtml = fs.readFileSync(livePath, 'utf8');
      const patched = patchColorsOnly(liveHtml, colors);
      if (patched === null) {
        alreadyPatched++;
        continue;
      }
      if (apply) fs.writeFileSync(livePath, patched, 'utf8');
      colorPatched++;
      log.push({ livePath, action: 'color-patched', colors });
    } else {
      let result;
      try {
        result = transform(originalHtml);
      } catch (err) {
        errors.push({ livePath, reason: `transform error: ${err.message}` });
        continue;
      }
      const out = wrapDocument(result.title, result.bodyHtml, result.colors);
      if (apply) fs.writeFileSync(livePath, out, 'utf8');
      regenerated++;
      log.push({ livePath, action: 'regenerated', colors: result.colors });
    }
  }

  console.log(`${apply ? 'Regenerated' : 'Would regenerate'} (auto-converted): ${regenerated}`);
  console.log(`${apply ? 'Color-patched' : 'Would color-patch'} (hand-rebuilt): ${colorPatched}`);
  console.log(`Already patched by a prior run (left untouched): ${alreadyPatched}`);
  console.log(`Hand-rebuilt pages with no colors to restore (left untouched): ${skippedNoColors}`);
  console.log(`Missing live file (skipped): ${missingLive.length}`);
  console.log(`Errors: ${errors.length}`);
  if (missingLive.length) console.log(JSON.stringify(missingLive, null, 2));
  if (errors.length) console.log(JSON.stringify(errors, null, 2));

  fs.writeFileSync('restore-colors-log.json', JSON.stringify({ log, missingLive, errors }, null, 2));
}

main();
